#!/bin/sh

set -e

case "$1" in
    configure)
        chown www-data:www-data /var/cache/xhgui
        chmod 700 /var/cache/xhgui
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
